tap 'caskroom/cask'
tap 'homebrew/bundle'
brew 'bash-completion'
brew 'colordiff'
brew 'coreutils'
brew 'curl'
brew 'git'
brew 'git-extras'
brew 'imagemagick'
brew 'openssl'
brew 'mas'
brew 'the_silver_searcher'
brew 'wget'
brew 'youtube-dl'
mas 'The Unarchiver', id: 425424353
mas 'Filedrop', id: 659443478
